# Generated by Django 5.2.2 on 2025-06-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='custom_application_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
