# Generated by Django 5.2.2 on 2025-06-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='default_form_schema',
            field=models.JSONField(default=dict, help_text='Default form fields for all job posts'),
        ),
    ]
