# Generated by Django 5.2.2 on 2025-06-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_default_form_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='instructions',
            field=models.TextField(blank=True, help_text="Instructions to be displayed on the agency's landing page."),
        ),
    ]
