# Generated by Django 5.2.2 on 2025-06-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
